from __future__ import annotations

from pathlib import Path


HOOK_TEMPLATE = """#!/usr/bin/env sh
# Generated by nbmirror. Re-run `nbmirror install-hook` to refresh.

changed_files=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -z "$changed_files" ]; then
  exit 0
fi

# shellcheck disable=SC2086
nbmirror hook-run --repo-root "{repo_root}" --notebooks-dir "{notebooks_dir}" --output-dir "{output_dir}" --home-target "{home_target}" $changed_files
status=$?
if [ $status -ne 0 ]; then
  exit $status
fi

has_output_changes=0
if ! git diff --quiet -- "{output_dir}"; then
  has_output_changes=1
fi
if [ -n "$(git ls-files --others --exclude-standard -- "{output_dir}")" ]; then
  has_output_changes=1
fi

if [ $has_output_changes -ne 0 ]; then
  echo "nbmirror updated mirror files."
  git add -- "{output_dir}"
  echo "nbmirror staged updated mirror files in {output_dir}."
  echo "Run commit again to include generated mirrors."
  exit 1
fi

exit 0
"""


def install_pre_commit_hook(
    repo_root: Path,
    notebooks_dir: str = "notebooks",
    output_dir: str = "notebooks_html",
    home_target: str = "index.html",
) -> Path:
    hooks_dir = repo_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / "pre-commit"

    script = HOOK_TEMPLATE.format(
        repo_root=repo_root.as_posix(),
        notebooks_dir=notebooks_dir,
        output_dir=output_dir,
        home_target=home_target,
    )
    hook_path.write_text(script.replace("\r\n", "\n"), encoding="utf-8")
    hook_path.chmod(0o755)
    return hook_path
